#Requires -Version 5.1
<#
.SYNOPSIS
    Installs or uninstalls Copilot CLI plugins from this repository.

.DESCRIPTION
    Three modes:

    DEFAULT (from GitHub):
      Detects the GitHub owner/repo from git remote origin, then runs
      'copilot plugin install' for each plugin directory. Requires the
      changes to already be pushed to GitHub.

      Before each install, any existing version of the plugin is uninstalled
      so the install is always clean. Superpowers is installed using the marketplace
      specifier (superpowers@superpowers-marketplace) to avoid repository plugin.json
      issues. Superpowers is installed by default unless -NoSuperpowers is provided.
      Dotnet is opt-in (use -Dotnet) to avoid installing large toolchains by default.

    UNINSTALL ALL (-UninstallAll flag):
      Uninstalls all currently installed Copilot CLI plugins. By default
      includes the superpowers marketplace plugin (disable with -NoSuperpowers).

    LOCAL (-Local flag):
      Generates a copilot-dev.ps1 wrapper script in the repo root that
      starts the Copilot CLI with --plugin-dir for every local plugin
      directory. Run .\copilot-dev.ps1 instead of copilot for local
      dev sessions. No GitHub push required.

.PARAMETER Plugin
    Optional. Process only the named plugin instead of all plugins.

.PARAMETER Local
    Generate the copilot-dev.ps1 wrapper for local dev sessions.

.PARAMETER NoSuperpowers
    Skip the superpowers marketplace plugin (applies to both install and uninstall).

.PARAMETER UninstallAll
    Uninstall all currently installed plugins instead of installing.

.EXAMPLE
    # Install all plugins from GitHub (after pushing), dotnet not included by default
    .\Install-Plugins.ps1

    # Install all plugins including dotnet
    .\Install-Plugins.ps1 -Dotnet

    # Install a single plugin from GitHub
    .\Install-Plugins.ps1 -Plugin custom-general-plugin

    # Install all plugins from GitHub (after pushing)
    .\Install-Plugins.ps1

    # Install a single plugin from GitHub

    # Install without the superpowers marketplace plugin
    .\Install-Plugins.ps1 -NoSuperpowers

    # Install including dotnet (opt-in — not installed by default)
        .\Install-Plugins.ps1 -Dotnet

    # Generate local dev wrapper for all plugins
    .\Install-Plugins.ps1 -Local


    # Uninstall all plugins (including superpowers)
    .\Install-Plugins.ps1 -UninstallAll

    # Uninstall all plugins except superpowers
    .\Install-Plugins.ps1 -UninstallAll -NoSuperpowers
#>

param(
    [string]$Plugin,
    [switch]$Local,
    [switch]$NoSuperpowers,
    [switch]$UninstallAll,
    [switch]$Dotnet,
    [switch]$DryRun
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$pluginsRoot = Join-Path $PSScriptRoot 'plugins'

# Defaults and feature flags
$dotnet = $false
if ($PSBoundParameters.ContainsKey('Dotnet')) { $dotnet = $Dotnet }
$dryRun = $false
if ($PSBoundParameters.ContainsKey('DryRun')) { $dryRun = $DryRun }

$pluginDirs = if ($Plugin) {
    @(Join-Path $pluginsRoot $Plugin)
} else {
    $dirs = Get-ChildItem $pluginsRoot -Directory | Select-Object -ExpandProperty FullName
    if (-not $dotnet) {
        $dirs = $dirs | Where-Object { (Split-Path $_ -Leaf) -ne 'dotnet' }
    }
    $dirs
}

# ── LOCAL MODE ────────────────────────────────────────────────────────────────
# Generates copilot-dev.ps1 in the repo root — a wrapper that starts the
# Copilot CLI with --plugin-dir for every local plugin directory.
# Run .\copilot-dev.ps1 instead of copilot for local dev sessions.
if ($Local) {
    $dirs = @()
    foreach ($dir in $pluginDirs) {
        $name = Split-Path $dir -Leaf
        $pluginJsonPath = Join-Path $dir '.github\plugin\plugin.json'
        if (-not (Test-Path $pluginJsonPath)) {
            Write-Warning "Skipping '$name' — no .github/plugin/plugin.json found."
            continue
        }
        $dirs += $dir
    }

    if ($dirs.Count -eq 0) { Write-Error "No valid plugins found."; exit 1 }

    $pluginArgs = ($dirs | ForEach-Object { "--plugin-dir `"$_`"" }) -join " "
    $wrapperPath = Join-Path $PSScriptRoot 'copilot-dev.ps1'

    @"
# copilot-dev.ps1 — generated by Install-Plugins.ps1 -Local
# Starts the Copilot CLI with all local plugin directories loaded.
# Re-generate by running: .\Install-Plugins.ps1 -Local
copilot $pluginArgs @args
"@ | Set-Content $wrapperPath -Encoding UTF8

    Write-Host "Generated: $wrapperPath" -ForegroundColor Green
    Write-Host "Use '.\copilot-dev.ps1' instead of 'copilot' for local dev sessions." -ForegroundColor Cyan
    return
}

# ── HELPERS ───────────────────────────────────────────────────────────────────
function Get-GithubRepo {
    $url = git remote get-url origin 2>&1
    if ($LASTEXITCODE -ne 0) { throw "No git remote 'origin' found. Are you inside a cloned git repository?" }
    if ($url -match 'github\.com[:/](.+?)(?:\.git)?$') { return $Matches[1] }
    throw "Could not parse a GitHub owner/repo from remote URL: $url"
}

# Returns the set of currently installed plugin names (the part before @ or space).
function Get-InstalledPluginNames {
    $output = copilot plugin list 2>&1
    $names = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
    foreach ($line in $output) {
        # Matches lines like: "  • plugin-name@source (v1.0.0)" or "  • plugin-name (v1.0.0)"
        if ($line -match '•\s+([^@\s(]+)') {
            [void]$names.Add($Matches[1])
        }
    }
    return $names
}

# Check whether a remote repository contains a plugin.json in common locations
function Test-RemotePluginJson {
    param([string]$Owner, [string]$Repo)
    $locations = @(
        ".github/plugin/plugin.json",
        "plugin.json",
        ".plugin/plugin.json",
        ".claude-plugin/plugin.json"
    )
    $branches = @("main","master")
    foreach ($branch in $branches) {
        foreach ($loc in $locations) {
            $url = "https://raw.githubusercontent.com/$Owner/$Repo/$branch/$loc"
            try {
                $resp = Invoke-WebRequest -Method Head -Uri $url -UseBasicParsing -ErrorAction Stop
                if ($resp.StatusCode -eq 200) { return $true }
            } catch {
                # continue searching other locations/branches
            }
        }
    }
    return $false
}

function Get-RemoteFileContent {
    param([string]$Owner,[string]$Repo,[string]$Branch,[string]$Path)
    $url = "https://raw.githubusercontent.com/$Owner/$Repo/$Branch/$Path"
    try {
        $resp = Invoke-WebRequest -Uri $url -UseBasicParsing -ErrorAction Stop
        if ($resp.StatusCode -eq 200) { return $resp.Content }
    } catch {
        # ignore and return null
    }
    return $null
}

function Find-RemoteSkillPath {
    param([string]$Owner,[string]$Repo,[string]$SkillName)
    try {
        $query = "repo:$Owner/$Repo filename:SKILL.md $SkillName"
        $uri = "https://api.github.com/search/code?q=$([System.Uri]::EscapeDataString($query))"
        $headers = @{ 'User-Agent' = 'copilot-cli' }
        $resp = Invoke-RestMethod -Uri $uri -Headers $headers -ErrorAction Stop
        if ($resp.total_count -gt 0) { return $resp.items[0].path }
    } catch {
        # ignore
    }
    return $null
}

function Populate-LocalSkillsFromRepo {
    param([string]$LocalPluginDir,[string]$Owner,[string]$Repo)

    $pluginJsonPath = Join-Path $LocalPluginDir '.github\plugin\plugin.json'
    if (-not (Test-Path $pluginJsonPath)) { return }
    try {
        $pj = Get-Content $pluginJsonPath -Raw | ConvertFrom-Json
    } catch {
        return
    }

    $localPluginName = Split-Path $LocalPluginDir -Leaf
    foreach ($skillRel in $pj.skills) {
        $skillName = Split-Path $skillRel -Leaf
        $skillsDir = Join-Path $LocalPluginDir 'skills'
        if (-not (Test-Path $skillsDir)) { New-Item -ItemType Directory -Path $skillsDir | Out-Null }
        $skillDir = Join-Path $skillsDir $skillName
        $skillFile = Join-Path $skillDir 'SKILL.md'
        if (Test-Path $skillFile) { continue }

        $content = $null

        # Candidate raw paths to try (in order). Many upstream repos place skills at 'skills/...'
        $candidatePaths = @(
            "skills/$skillName/SKILL.md",
            "$skillName/SKILL.md",
            "plugins/$localPluginName/skills/$skillName/SKILL.md",
            ".github/plugins/$localPluginName/skills/$skillName/SKILL.md"
        )

        # Special-case: some upstream plugins place skills under plugins/<plugin>/skills/<different-name>/SKILL.md
        # If an exact path is known across the repo, try it (user-provided mapping).
        if ($skillName -ieq 'security-best-practices') {
            $candidatePaths += 'plugins/security-best-practices/skills/ai-prompt-engineering-safety-review/SKILL.md'
        }

        foreach ($branch in @('main','master')) {
            foreach ($path in $candidatePaths) {
                $content = Get-RemoteFileContent -Owner $Owner -Repo $Repo -Branch $branch -Path $path
                if ($content) { break }
            }
            if ($content) { break }
        }

        # If not found via candidate paths, use code-search fallback to locate SKILL.md path
        if (-not $content) {
            $found = Find-RemoteSkillPath -Owner $Owner -Repo $Repo -SkillName $skillName
            if ($found) {
                foreach ($branch in @('main','master')) {
                    $content = Get-RemoteFileContent -Owner $Owner -Repo $Repo -Branch $branch -Path $found
                    if ($content) { break }
                }
            }
        }

        if ($content) {
            New-Item -ItemType Directory -Path $skillDir -Force | Out-Null
            $content | Set-Content -Path $skillFile -Encoding UTF8
            Write-Host "Fetched skill '$skillName' into $skillFile" -ForegroundColor Green
        } else {
            throw "Missing remote SKILL.md for '$skillName' in $Owner/$Repo. Install aborted — upstream repository does not contain the required skill file."
        }
    }
}

function Invoke-PluginReinstall {
    param(
        [string]$Name,
        [string]$Ref,
        [System.Collections.Generic.HashSet[string]]$Installed
    )
    # Ensure $Installed is a valid set; lazily populate if not provided
    if ($null -eq $Installed) {
        try {
            $Installed = Get-InstalledPluginNames
        } catch {
        $Installed = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
        }
    }

    if ($dryRun) {
        Write-Host "[DryRun] Would reinstall '$Name' from '$Ref'." -ForegroundColor Cyan
    return $true
    }

    try {
        if ($Installed -and $Installed.Contains($Name)) {
            Write-Host "  Uninstalling existing '$Name' ..." -ForegroundColor Yellow
            copilot plugin uninstall $Name
        }
    } catch {
        Write-Warning "Failed to detect/uninstall existing plugin '$Name': $_"
    }

    Write-Host "Installing $Ref ..." -ForegroundColor Cyan
    try {
        copilot plugin install $Ref
    return $true
} catch {
    Write-Warning ("Install failed for {0}: {1}" -f $Ref, $_)
    return $false
}
}

# ── UNINSTALL-ALL MODE ────────────────────────────────────────────────────────
if ($UninstallAll) {
    $installed = Get-InstalledPluginNames
    if ($installed.Count -eq 0) {
        Write-Host "No plugins currently installed." -ForegroundColor Yellow
        return
    }

    $toRemove = if ($NoSuperpowers) {
        $installed | Where-Object { $_ -ne 'superpowers' }
    } else {
        $installed
    }

    $count = 0
    foreach ($name in $toRemove) {
        Write-Host "Uninstalling '$name' ..." -ForegroundColor Yellow
        copilot plugin uninstall $name
        $count++
    }

    Write-Host ""
    Write-Host "$count plugin(s) uninstalled." -ForegroundColor Green
    return
}

# ── GITHUB MODE ───────────────────────────────────────────────────────────────
$repo      = Get-GithubRepo
$installed = Get-InstalledPluginNames
$count     = 0

foreach ($dir in $pluginDirs) {
    $name = Split-Path $dir -Leaf
    $pluginJsonPath = Join-Path $dir '.github\plugin\plugin.json'

    if (-not (Test-Path $pluginJsonPath)) {
        Write-Warning "Skipping '$name' — no .github/plugin/plugin.json found."
        continue
    }

    # If the local plugin lacks a skills directory, attempt to populate it from the repository
    try {
        $pj = Get-Content $pluginJsonPath -Raw | ConvertFrom-Json
        if ($pj.repository -and ($pj.repository -is [string])) {
            if ($pj.repository -match 'github\.com[:/](.+?)(?:\.git)?$') {
                $ownerRepo = $Matches[1]
                $parts = $ownerRepo.Split('/')
                if ($parts.Count -ge 2) {
                    $owner = $parts[0]; $repoName = $parts[1]
                    Populate-LocalSkillsFromRepo -LocalPluginDir $dir -Owner $owner -Repo $repoName
                }
            }
        }
    } catch {
        Write-Error "Remote skill fetch failed for plugin '$name': $($_.Exception.Message)"
        Write-Host "Skipping installation of '$name' due to missing upstream skills." -ForegroundColor Yellow
        continue
    }

    $ok = Invoke-PluginReinstall -Name $name -Ref "${repo}:plugins/${name}" -Installed $installed
    if ($ok) { $count++ } else { Write-Warning "Plugin install failed or skipped: $name" }
}

# ── SUPERPOWERS MARKETPLACE ───────────────────────────────────────────────────
if (-not $NoSuperpowers) {
    # Prefer marketplace install using the marketplace specifier (works like command line: superpowers@superpowers-marketplace)
    $marketRef = 'superpowers@superpowers-marketplace'
    $ok = $false
    try {
        $ok = Invoke-PluginReinstall -Name 'superpowers' -Ref $marketRef -Installed $installed
    } catch {
        Write-Warning ("Marketplace install attempt for {0} raised an error: {1}" -f $marketRef, $_)
        $ok = $false
    }
    if (-not $ok) {
        $owner = 'obra'; $repoName = 'superpowers-marketplace'
        $hasPluginJson = Test-RemotePluginJson -Owner $owner -Repo $repoName
        if (-not $hasPluginJson) {
            Write-Warning "Skipping 'superpowers' — No plugin.json found in $owner/$repoName (common locations). Install skipped."
        } else {
            $ok = Invoke-PluginReinstall -Name 'superpowers' -Ref "$owner/$repoName" -Installed $installed
        }
    }
    if ($ok) { $count++ } else { Write-Warning "Superpowers plugin not installed." }
}

Write-Host ""
$finalInstalled = Get-InstalledPluginNames
$visibleCount = $finalInstalled.Count
Write-Host "$visibleCount plugin(s) installed." -ForegroundColor Green

