#!/usr/bin/env bash
# install-plugins.sh — Install or load Copilot CLI plugins from this repository.
#
# LOCAL (--local flag):
#   Generates copilot-dev.sh in the repo root — a wrapper that starts copilot
#   with --plugin-dir for every local plugin. Run ./copilot-dev.sh instead of
#   copilot for dev sessions. No push to GitHub needed.
#
# DEFAULT (from GitHub):
#   Reads git remote origin, derives owner/repo, runs 'copilot plugin install'.
#   Requires changes to be pushed to GitHub first.
#
# Usage:
#   ./install-plugins.sh [--local] [<plugin-name>]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGINS_ROOT="$SCRIPT_DIR/plugins"

LOCAL=false
FILTER=""

for arg in "$@"; do
    case "$arg" in
        --local) LOCAL=true ;;
        *)       FILTER="$arg" ;;
    esac
done

# LOCAL MODE
# Generates copilot-dev.sh that starts copilot with --plugin-dir for each local plugin.
if [ "$LOCAL" = true ]; then
    PLUGIN_ARGS=""
    for dir in "$PLUGINS_ROOT"/*/; do
        name=$(basename "$dir")
        [ -n "$FILTER" ] && [ "$name" != "$FILTER" ] && continue
        plugin_json="$dir/.github/plugin/plugin.json"
        if [ ! -f "$plugin_json" ]; then
            echo "WARN: Skipping '$name' — no .github/plugin/plugin.json found." >&2
            continue
        fi
        PLUGIN_ARGS="$PLUGIN_ARGS --plugin-dir \"$dir\""
    done

    if [ -z "$PLUGIN_ARGS" ]; then
        echo "ERROR: No valid plugins found." >&2; exit 1
    fi

    WRAPPER="$SCRIPT_DIR/copilot-dev.sh"
    printf '#!/usr/bin/env bash\n# copilot-dev.sh — generated by install-plugins.sh --local\n# Re-generate: ./install-plugins.sh --local\nexec copilot %s "$@"\n' "$PLUGIN_ARGS" > "$WRAPPER"
    chmod +x "$WRAPPER"
    echo "Generated: $WRAPPER"
    echo "Use './copilot-dev.sh' instead of 'copilot' for local dev sessions."
    exit 0
fi

# GITHUB MODE
get_github_repo() {
    local url
    url=$(git remote get-url origin 2>/dev/null) \
        || { echo "ERROR: No git remote 'origin' found." >&2; exit 1; }
    if [[ "$url" =~ github\.com[:/](.+?)(\.git)?$ ]]; then
        echo "${BASH_REMATCH[1]}"
    else
        echo "ERROR: Remote URL is not a GitHub URL: $url" >&2; exit 1
    fi
}

REPO=$(get_github_repo)
INSTALLED=0

for dir in "$PLUGINS_ROOT"/*/; do
    name=$(basename "$dir")
    [ -n "$FILTER" ] && [ "$name" != "$FILTER" ] && continue
    plugin_json="$dir/.github/plugin/plugin.json"
    if [ ! -f "$plugin_json" ]; then
        echo "WARN: Skipping '$name' — no .github/plugin/plugin.json found." >&2
        continue
    fi
    ref="${REPO}:plugins/${name}"
    echo "Installing $ref ..."
    copilot plugin install "$ref"
    INSTALLED=$((INSTALLED + 1))
done

echo ""
echo "$INSTALLED plugin(s) installed from $REPO."